### ISSUE TITLE
Backup of root volume fails if when using `btrfs-prog 4.16`.

### ISSUE THREAD

**Issue by R1dO** [wesbarnett/snap-sync#68]
Reporting this in case other people run into the same problem, since i am not sure if it is something that can (or should) be fixed here.

When a system is using `btrfs-prog 4.16` any backups of a root volume `/` will fail with the following error:
```bash
Sending incremental snapshot for 'root' configuration...
ERROR: not on mount point: /
ERROR: empty stream is not considered valid
Exited due to error on line 458.
exit status: 1
command: $ssh btrfs receive "$backup_location"
bash line: 0
function name: main
```

It is a known regression error in btrfs which is fixed in 4.17.
See: https://github.com/kdave/btrfs-progs/pull/138

**Comment by NicoHood** [comment]
Which kernel do you have? This seems to be end of life.

**Comment by R1dO** [comment]
The one that comes with the latest updates on ubuntu 18.10. Not sure about the exact version (will check when i am at home).

Besides that:
btrfs-progs v4.16 is from Apr 2018 according to the [changelog](https://btrfs.wiki.kernel.org/index.php/Changelog#By_version_.28btrfs-progs.29), would that not be a bit early for EOL?

update (adding kernel version)
```
$ uname -srvpio
Linux 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 GNU/Linux
```

**Comment by wesbarnett** [comment]
This seems fixed upstream? Nothing I can do here.

**Comment by brookst** [comment]
As a work-around until btrfs-progs 4.17 makes it into other distros, you can use alternate mount paths in your snapper configs. If you mount the root of your btrfs filesystem somewhere, e.g:

    # mkdir -p /media/btrfs/root
    # mount -t btrfs -o subvolid=5 /dev/sda1 /media/btrfs/root

Then you can edit the configs in `/etc/snapper/configs` to use the extra path for the `SUBVOLUME` variable. E.g. my system root subvolume is named `@`, so my config sets `SUBVOLUME="/media/btrfs/root/@"`. Likewise, home is named `@home`, so that config sets `SUBVOLUME="/media/btrfs/root/@home"`. This avoids the "not on mount point: /" error and everything else works as it should (it works for me™).

Remember to add the mount to your `/etc/fstab` so that it comes up after rebooting.
